# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ProjetosEstagio5CGEO
                                 A QGIS plugin
 Solução dos Estagiarios do 5 CGEO
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-04-04
        copyright            : (C) 2023 by Estagiarios 5 CGEO
        emails               : e.tadeu.eb@ime.eb.br
                               joao.pereira@ime.eb.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Estagiarios do 5 CGEO'
__date__ = '2023-04-04'
__copyright__ = '(C) 2023 by Estagiarios 5 CGEO'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
from code import interact
from qgis.PyQt.QtCore import QCoreApplication
from qgis.PyQt.Qt import QVariant, QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSink,
                       QgsPoint,
                       QgsFeature,
                       QgsExpression,
                       QgsVectorLayer,
                       QgsProcessingParameterDistance,
                       QgsProcessingMultiStepFeedback,
                       QgsProcessingParameterVectorLayer,
                       QgsProject,
                       QgsFields,
                       QgsFeature,
                       QgsField,
                       QgsGeometry,
                       QgsGeometryUtils,
                       QgsWkbTypes)
import processing
from PyQt5.QtGui import QColor

class Projeto8Solucao(QgsProcessingAlgorithm):
    """
    
    Este algoritmo realiza a revisão de ligação entre produtos.

    """
    # Camadas de input
    VIAS = 'VIAS'
    INPUT_MAX_SIZE = 'INPUT_MAX_SIZE'
    # Camadas de output
    OUTPUT = 'OUTPUT'

    def initAlgorithm(self, config):
        
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.VIAS, 
                self.tr('Insira a camada de vias'), 
                types=[QgsProcessing.TypeVectorLine], 
                defaultValue=None)
            )
        
        self.addParameter(
            QgsProcessingParameterDistance(
                'INPUT_MAX_SIZE',
                self.tr('Insira o comprimento máximo das vias pequenas'), 
                parentParameterName = 'VIAS',
                optional = False,
                minValue=0,
                defaultValue=0.005)
            )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT, 
                self.tr('Vias com cruzamentos corrigidos'), 
                type=QgsProcessing.TypeVectorLine, 
                createByDefault=True, 
                supportsAppend=True, 
                defaultValue='TEMPORARY_OUTPUT')
            )
        
        
    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        vias = self.parameterAsVectorLayer(parameters,self.VIAS,context)
        alcance_max = self.parameterAsDouble(parameters,self.INPUT_MAX_SIZE, context)

        #Criação da camada de saída do tipo ponto com o tipo de erro
        #fields = vias.fields()
        #(output_sink, output_dest_id) = self.parameterAsSink(parameters,
        #                                                    self.OUTPUT,
        #                                                    context,
        #                                                    fields,
        #                                                    2, #2 é para tipo linha, 1 é para tipo ponto
        #                                                    vias.sourceCrs())

        #Criação da lista de feições de linhas pequenas
        smallLines = list()       
        for lyr in vias.getFeatures():
            length = lyr.geometry().length()
            if length < alcance_max: smallLines.append(lyr)

        vias.startEditing()
        for linesmall in smallLines:
            point_reference = False
            geomline = linesmall.geometry()
            bbox = geomline.boundingBox()

            for line in vias.getFeatures(bbox):
                geomline2 = line.geometry()
                if geomline.equals(geomline2): continue

                
                if point_reference == False: 
                    pointflag = geomline.intersection(geomline2)
                    if pointflag.wkbType() == QgsWkbTypes.Point: point_reference = True
                    elif pointflag == QgsWkbTypes.LineString or pointflag == QgsWkbTypes.MultiLineString:
                        for parts in pointflag.parts: vertex = list(parts)
                        pointflag = QgsGeometry.fromPoint(vertex[0])
                        point_reference = True
                
                else:
                    if geomline2.intersects(pointflag): continue
                    else:
                        for parts in geomline2.parts(): vertices = list(parts)
                        for i in range (0, len(vertices)):
                            if bbox.xMinimum() <= vertices[i].x() <= bbox.xMaximum() and bbox.yMinimum() <= vertices[i].y() <= bbox.yMaximum(): vertices[i] = QgsPoint(pointflag.asPoint())
                        new_line = QgsGeometry.fromPolyline(vertices)          
                        line.setGeometry(new_line)
                        vias.updateFeature(line)

            #Deletando as linhas pequenas
            for line in vias.getFeatures(bbox):
                geomline2 = line.geometry()
                if geomline.equals(geomline2): vias.deleteFeature(line.id())
                    
        return {self.OUTPUT: vias}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Corrigir cruzamentos'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return 'Corrigir cruzamentos'

    """def groupId(self):
        
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        
        return 'Projeto 6'"""

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return Projeto8Solucao()
